name: Build APK

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Restore Keystore from Secret
      run: echo "$KEYSTORE_BASE64" | base64 --decode > peakform-release.keystore
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

    - name: Check KEYS in env
      run: |
        echo "KEY_ALIAS is set? [${KEY_ALIAS:+yes}]" 
        echo "KEYSTORE_PASSWORD is set? [${KEYSTORE_PASSWORD:+yes}]"
        echo "KEY_PASSWORD is set? [${KEY_PASSWORD:+yes}]"
      env:
        KEYSTORE_PATH: ${{ github.workspace }}/peakform-release.keystore
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    - name: Build Release APK
      run: |
        ./gradlew assembleRelease \
        -PkeystorePath="$KEYSTORE_PATH" \
        -PkeystorePassword="$KEYSTORE_PASSWORD" \
        -PkeyAlias="$KEY_ALIAS" \
        -PkeyPassword="$KEY_PASSWORD"
      env:
        KEYSTORE_PATH: ${{ github.workspace }}/peakform-release.keystore
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: PeakForm-release-apk
        path: app/build/outputs/apk/release/app-release.apk
