name: Build & Release APK

on:
  push:
    branches: [ main ]   # still builds APK for main
    tags:
      - 'v*'             # also triggers when you push a tag like v1.0.0
  workflow_dispatch:      # still allows manual runs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Restore Keystore from Secret
      run: echo "$KEYSTORE_BASE64" | base64 --decode > peakform-release.keystore
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

    - name: Build Release APK
      env:
        KEYSTORE_PATH: ${{ github.workspace }}/peakform-release.keystore
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: PeakForm-release-apk
        path: app/build/outputs/apk/release/app-release.apk

    # 🚀 ONLY runs when triggered by a tag (i.e., a release)
    - name: Upload APK as Release Asset
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: app/build/outputs/apk/release/app-release.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
